[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
process_queue = {path = "../process_queue" }
tokio = { version = "1.43.0", features = ["full"] }
env_logger = "0.10"
log = "0.4"
